# Generated by Django 5.2.5 on 2025-08-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_categoryservice_service_category_serviceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.CharField(default='Sur devis', max_length=100),
        ),
    ]
