# Generated by Django 5.2.5 on 2025-11-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={},
        ),
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
