from rest_framework_simplejwt.views import TokenObtainPairView
from .token_serializers import EmailOrUsernameTokenObtainPairSerializer

class CustomTokenObtainPairView(TokenObtainPairView):
    serializer_class = EmailOrUsernameTokenObtainPairSerializer
